### ISSUE TITLE
Emergency Backup Not Saving New Spawn Point

### ISSUE THREAD

**Issue by xLenso** [blaxxun-boop/ServerCharacters#11]
Hi, not sure if you still view nexusmod or receiving any notification from here.
I have 1 simple question to ask about the mod "Server side Character".

I understand that you mentioned in the description that the mod will generate "backup" / "emergency" for players disconnect situation.

From playing with your mod, the basic understanding we know about the backup is saving all the items but the character will be sent back to the last saved spawnpoint.

Recently I have a friend happened to have this problem as below:
1. Previously saved his spawnpoint at Base A, he then built a new base B and saved a new spawnpoint at base B
2. Weird that when he got disconnected, no matter how many times he saved in base B, the mod will send him back to base A

So our question is that, how does the mod actually recognize the new spawnpoint? any specific action or order to let the mod save the new spawnpoint so that will not be sent back to the old spawnpoint?

Also, I can't find any way to contact you from Thunderstore webpage interface, it seems they dont have the comments / messages function on their webpage.

If there is any other way that we can contact you, please let us know :) Thank you so much for your efforts and time on creating and maintaining mods.

**Comment by blaxxun-boop** [comment]
So, after investigating this:
Valheim actually does not save your spawn point during its periodic world saves. And it does this, so you don't spawn there, if you die after the periodic save. So, they do that on purpose.

That being said, I agree that this shouldn't be this way and will put code to change this behaviour with the next ServerCharacters release.
