### ISSUE TITLE
Character Desync Issues

### ISSUE THREAD

**Issue by CyleJS** [blaxxun-boop/ServerCharacters#13]
A few days ago I updated this mod on my dedi server with the most recent update, but I have a few players who continued playing for a day or so still using the old version. Now, although they've updated, they are both reporting regular issues of logging in to find themselves with inventory irregularities or entering the world in locations far away from where they had logged out at.

I have tried reinstalling the mod on the server, having them completely reinstall the game and their BepInEx folder, messing around with their backups on the server. Nothing is helping. They continue to have issues almost every time they log in. Any ideas of what can be done?

**Comment by blaxxun-boop** [comment]
Can you send me one of the affected players save file, so I can have a look at it?

And their BepInEx log file after having quit the game would be insanely helpful.

**Comment by CyleJS** [comment]
> Can you send me one of the affected players save file, so I can have a look at it?
> 
> And their BepInEx log file after having quit the game would be insanely helpful.

Absolutely. I have the files, but GitHub won't let me attach these file types here. I also don't see a way to DM you. Is there an email address I could contact you at? Or send me an email to cyledriver@gmail.com and I'll send you the files from there? Thanks for your help!

**Comment by blaxxun-boop** [comment]
You can find me on Discord, if you want to: blaxxun#9098

**Comment by CyleJS** [comment]
I sent you a PM on Discord. Thanks again for the help!

**Comment by blaxxun-boop** [comment]
I got your files, just cannot reply on Discord, because you block direct messages from other people.

Will hopefully find some time to look into this in the next few days.

**Comment by CyleJS** [comment]
Apologies. I added a mutual server between us so that you'll be able to message me now. Sorry about that, and thanks for looking into it.

**Comment by blaxxun-boop** [comment]
I made some changes to the way the character position is handled during a world save. Not sure, if that will fix your issue, but might be worth a shot.
