### ISSUE TITLE
Add to Existing Server?

### ISSUE THREAD

**Issue by lightsourced** [blaxxun-boop/ServerCharacters#14]
Is there a way to add this to an existing server without forcing people to make new characters?

**Comment by blaxxun-boop** [comment]
There is a backup only mode that doesn't enforce anything on players. Just note that this also means that it doesn't prevent players from bringing items on your server. But you can enable the backup only mode, have every player login once, until the players knows all characters and then disable the backup only mode.

Depending on how many players your server has, you can also have them send you their profile and upload it to the server yourself, so the server knows their character. Just make sure to prefix the save file with their Steam ID.

**Comment by lightsourced** [comment]
Ok awesome, that's how I figured it would work, it's just friends and mostly so that they don't end up losing their stuff by accidentally logging in with the wrong character. Thanks for the quick response!
