### ISSUE TITLE
Request : accept existing character

### ISSUE THREAD

**Issue by JLuc** [blaxxun-boop/ServerCharacters#17]
I have installed ServerCharacters on an existing world'server. This world is inhabited by existing characters, but we now have decided to not enable anymore to bring stuff from other worlds. 
A message pops when they try to connect : « Please create a new character, before connecting to this server, to avoid loss of data »

I'd like to be able to start the game ServerCharacters and enable existing characters to connect. And once entered in the game, their identity are recorded on the server along with their characteristics, so these are used for later connects.

Hence this feature request : 
Optionaly allow any existing character to enter the world (only the first time), 
OR enable to declare existing characters that are allowed to enter the world.

**Comment by blaxxun-boop** [comment]
Enable Backup only mode in the config. Once the server has all characters saved, disable it again.
