### ISSUE TITLE
Case sensitivity on savefile names breaks some characters loading in 1.2.7 and 1.2.8

### ISSUE THREAD

**Issue by nonplayer** [blaxxun-boop/ServerCharacters#19]
Starting with version 1.2.7 and continuing with version 1.2.8, I am now getting this on characters with two-word names:

`08/08/2022 09:28:38:   failed to load: /home/container/.config/unity3d/IronGate/Valheim/characters_local/76561198011262369_npc grunzolde.fch (Could not find file "/home/container/.config/unity3d/IronGate/Valheim/characters_local/76561198011262369_npc grunzolde.fch")`

Attempting to connect reverts back to the login with an on-screen message telling the player to make a new character from scratch.

The file exists, but it is `76561198011262369_Npc Grunzolde.fch` - the file is camel case, as this was the case the game itself saved the file as.

I can rename the existing file on the server to be all lower case, and then it works, but all map data is also locked. But the game itself wrote these character save files with all lower-case names, so it happens again with other multi-name characters old and new. We have 30 characters on the server, all saved in camel case, renaming them and forcing map loss would be a major setback. Currently the only way for everyone on our server to play is to revert to 1.2.6, where the issue is not encountered.

It seems that it forces case sensitivity on multi-word character names, is my guess. I don't see a changelog anywhere though.

**Comment by david-benes** [comment]
Having a similar issue. The file exists, but it fails to set the last write time on disconnect event for some reason.
It is possibly unrelated to the issue above. Nevertheless, @nonplayer did not attach any stacktrace (maybe there wasn't any)  so I can't tell for sure.

```
FileNotFoundException: Could not find file "C:\Users\TCAGame_Svc4477667\AppData\LocalLow\IronGate\Valheim\characters_local\76561198024106101_player.fch"
  at System.IO.File.SetLastWriteTime (System.String path, System.DateTime lastWriteTime) [0x00017] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at ServerCharacters.ServerSide+PatchZNetDisconnect.Prefix (ZNetPeer peer) [0x000af] in <3d9b2c03e7b14e3e985fea53d4cd8576>:0 
  at (wrapper dynamic-method) ZNet.DMD<ZNet::Disconnect>(ZNet,ZNetPeer)
  at ZNet.UpdatePeers (System.Single dt) [0x00041] in <cd9c5dec6e13468abeab88739b142a63>:0 
  at ZNet.Update () [0x00021] in <cd9c5dec6e13468abeab88739b142a63>:0 
```

**Comment by nonplayer** [comment]
I didn't have a stack trace to attach, unfortunately.

**Comment by pwlgrzs** [comment]
Also having this issue but I suspect in my case it is related to the fact character saves are in a different directory.

`[Error  : Unity Log] FileNotFoundException: Could not find file "/home/vhserver/.config/unity3d/IronGate/Valheim/characters_local/XXX_martam.fch"
Stack trace:
System.IO.File.SetLastWriteTime (System.String path, System.DateTime lastWriteTime) (at <695d1cc93cca45069c528c15c9fdd749>:0)
ServerCharacters.ServerSide+PatchZNetDisconnect.Prefix (ZNetPeer peer) (at <3d9b2c03e7b14e3e985fea53d4cd8576>:0)
(wrapper dynamic-method) ZNet.DMD<ZNet::Disconnect>(ZNet,ZNetPeer)
ZNet.UpdatePeers (System.Single dt) (at <cd9c5dec6e13468abeab88739b142a63>:0)
ZNet.Update () (at <cd9c5dec6e13468abeab88739b142a63>:0)`

Is it looking for `/home/vhserver/.config/unity3d/IronGate/Valheim/characters_local/76561199191585389_martam.fch` but the actual path is `/home/vhserver/save/characters_local/XXX_martam.fch`.

Server is started with `-savedir` parameter.

**Comment by david-benes** [comment]
Great observation @pwlgrzs ! Base on you comment, I reviewed my server configuration (I'm running my server on a ready-made, hosted server). My configuration is using -savedir parameter as well, pointing outside of regular save folder. The issue we both have appears to be the same.

**Comment by david-benes** [comment]
The issue appears to be in the backupProfile method:
https://github.com/blaxxun-boop/ServerCharacters/blob/master/ServerCharacters/ServerSide.cs#L548:

I believe this is the correct method to obtain actual save dir based on profile provided from the server:
`PlayerProfile.GetCharacterFolderPath(profile.m_fileSource)`

While this seems to contain an incorrect path when -savedir is used because it is using current directory instead:
`Utils.CharacterSavePath`

I have no way to test, though.

**Comment by blaxxun-boop** [comment]
Sorry that this took so long to fix. Was kinda busy with other stuff. Should be fine in v1.2.9 now.
