### ISSUE TITLE
Backups are not created when -savedir is specified

### ISSUE THREAD

**Issue by david-benes** [blaxxun-boop/ServerCharacters#20]
According to the documentation, this mod should create server character backups automatically.
However, there are no backups appearing.

From what I saw in the code, backups shoud appear in the characters_local/backups. I tried creating the directory but it did not help.
I'm not sure what details should I provide to help with the resolution. There are no errors  in the log except for one regarding the last write date (#19).

**Comment by david-benes** [comment]
As we figured out in #19, the are some discrepancies about save folder in backupProfile method when -savedir server option is specified.

**Comment by blaxxun-boop** [comment]
Sorry that this took so long to fix. Was kinda busy with other stuff. Should be fine in v1.2.9 now.

**Comment by david-benes** [comment]
@blaxxun-boop Awesome! Thank you. I will test this during server maintenance window.
