### ISSUE TITLE
existing players are not able to connect after adding this mod

### ISSUE THREAD

**Issue by smobcraft** [blaxxun-boop/ServerCharacters#21]
Added this mod to the server and any existing players who were playing on our server before can't connect. I was able to get around it by having my players switch their characters to local characters and sending me their character files, adding them to server manually but wondering if this is supposed to happen automatically or the manual adding of player characters to the server is supposed to happen?

I couldn't find anything about it in the README

Thanks,

Mike

**Comment by blaxxun-boop** [comment]
That's exactly what the mod is supposed to do: Keep existing characters out, so you cannot bring items / skills into the world.
If you add this to an existing world, you can either use the manual import method for profiles, which is described in the README or enable the backup only mod, until the server knows all characters and then disable it again.

**Comment by smobcraft** [comment]
Thank you!
