### ISSUE TITLE
Mistlands Update: Error with Raising Skills Causes Start Loop

### ISSUE THREAD

**Issue by BranTuna** [blaxxun-boop/ServerCharacters#26]
Using The Character Template, I've simply set all non-Profession skills to start at 1, and have also set the world spawn, and for characters to start with 5 Coins. Set up the server after a complete wipe and reinstall, and every time the Valkyrie drops off my character, it errors out in the local console, however the error doesn't show up server-side.

```
[Error  : Unity Log] MissingMethodException: void Skills.CheatRaiseSkill(string,single)
Stack trace:
(wrapper dynamic-method) Game.DMD<Game::SpawnPlayer>(Game,UnityEngine.Vector3)
Game.UpdateRespawn (System.Single dt) (at <89fc507b04c049dea6a613ec7447ff8b>:0)
Game.FixedUpdate () (at <89fc507b04c049dea6a613ec7447ff8b>:0)
```

**Comment by blaxxun-boop** [comment]
I will start testing and updating my mods for the PTB starting on the weekend / early next week. If there is no easy way to make them work on the current version of Valheim AND the PTB, the update for the mod will be released once Mistlands goes live, though.

For now, please consider all of my mods broken on the PTB.
