### ISSUE TITLE
Mistlands update?

### ISSUE THREAD

**Issue by Vanaheymr** [blaxxun-boop/ServerCharacters#28]
In the new version of the game, the mod is broken: after creating a character and connecting to the server, the intro is played in circles

How soon will this mod be updated for the new version of the game?

---

11/26/2022 20:31:04: World pos (-169.2, 190.0, 804.5)   (-168.9, 189.4, 804.4)
MissingMethodException: void Skills.CheatRaiseSkill(string,single)
  at (wrapper dynamic-method) Game.DMD<Game::SpawnPlayer>(Game,UnityEngine.Vector3)
  at Game.UpdateRespawn (System.Single dt) [0x0002a] in <89fc507b04c049dea6a613ec7447ff8b>:0 
  at Game.FixedUpdate () [0x00082] in <89fc507b04c049dea6a613ec7447ff8b>:0 

11/26/2022 20:31:04: Destroying old local player
11/26/2022 20:31:04: Destroying valkyrie
11/26/2022 20:31:11: Loading dungeon
11/26/2022 20:31:11: Dungeon loaded 11
11/26/2022 20:31:11: Dungeon load time 61,4073 ms
11/26/2022 20:31:22: Spawned Deer x 2
11/26/2022 20:31:22: Spawned Boar x 2
11/26/2022 20:32:00: Spawned Fish3 x 1
11/26/2022 20:32:19: Starting descent
11/26/2022 20:32:38: We are here
11/26/2022 20:32:38: We are here
11/26/2022 20:32:38: Starting music morning
11/26/2022 20:32:40: Setting up valkyrie 
11/26/2022 20:32:40: Show intro 16288

**Comment by blaxxun-boop** [comment]
Please stop reporting issues for the PTB, thanks.

**Comment by Vanaheymr** [comment]
Oh, sorry, my mistake :)

**Comment by Vanaheymr** [comment]
You really nice guy, thx for your mods and their support
