### ISSUE TITLE
[Feature - Request] player.log / LogOutput.log on successful client-server connection

### ISSUE THREAD

**Issue by virtualbjorn** [blaxxun-boop/ServerCharacters#3]
A way for server admins to verify certain player logs on successful connection to the server.

It doesn't have to  track log changes as the player plays on the player. Just the log when the server and client successfully connected to each other.

**Comment by blaxxun-boop** [comment]
Not entirely sure what you mean by that. You want the BepInEx log output to be uploaded to the server?
Because I won't do that. There might be personal data in there, like file paths that expose the users name.

**Comment by virtualbjorn** [comment]
Will it be possible to have the list of mods extracted from the logoutput file instead?

**Comment by blaxxun-boop** [comment]
Not really. If you want to blacklist / whitelist mods, try Azus ServerBuddy or Anti-Cheat.
