### ISSUE TITLE
The server will not create a role archive

### ISSUE THREAD

**Issue by yuansox** [blaxxun-boop/ServerCharacters#32]
Failed to send session data. Error: /Event/WriteTelemetryEvents: The requesting entity is not authorized to write events with namespace playfab.party. Allowed namespaces can be 'custom' or begin with 'custom.'.

**Comment by blaxxun-boop** [comment]
That's a vanilla crossplay error.

I'd recommend to disable crossplay, if you do not need it. It doesn't work properly at all.
