### ISSUE TITLE
getting incompatible version message with linux client

### ISSUE THREAD

**Issue by bserret** [blaxxun-boop/ServerCharacters#33]
trying to log onto a server via r2modmanplus with about 7 mods I get the message incompatible version - I am running on linux ubuntu 22 via steam.  Windows based clients with the same mods appear to be working.  It seems to connect and accepts password (the server) then disconnects with incompatible version message. In the logs I find a reference to servercharacters. Any suggestions appreciated.

[Info   : Unity Log] 12/26/2022 10:55:19: Connecting to server with Steam-backend XXX.XXX.143.187:34500

[Info   : Unity Log] 12/26/2022 10:55:19: Starting to connect to XXX.XXX.143.187:34500

[Info   : Unity Log] 12/26/2022 10:55:19: Got status changed msg k_ESteamNetworkingConnectionState_Connecting

[Info   : Unity Log] 12/26/2022 10:55:19: New connection

[Info   : Unity Log] 12/26/2022 10:55:19: Session auth respons callback

[Info   : Unity Log] Received Server Characters version 1.3.3 and minimum version 1.3.3 from the server.
[Info   : Unity Log] 12/26/2022 10:55:19: Got status changed msg k_ESteamNetworkingConnectionState_Connected

[Info   : Unity Log] 12/26/2022 10:55:19: Connected

[Info   : Unity Log] 12/26/2022 10:55:19: Got connection SteamID 9016745905XXXXXX

[Info   : Unity Log] 12/26/2022 10:55:27: Got connectoin error msg ErrorVersion

[Info   : Unity Log] 12/26/2022 10:55:27: Lost connection to server:ErrorVersion

[Message:Server Characters] Lost connection to the server. Preparing for emergency backup of profile data.
[Info   : Unity Log] 12/26/2022 10:55:27: Shuting down

**Comment by blaxxun-boop** [comment]
Where is the reference to ServerCharacters?

Check the server log and it will tell you the issue.
