### ISSUE TITLE
dedicated server +crossplay issue

### ISSUE THREAD

**Issue by helix22** [blaxxun-boop/ServerCharacters#36]
Servercharacters does not save character data on a dedicated server running on windows (crossplay enabled)

**Comment by helix22** [comment]
[bump]

Server message (reasonably enough :P):

01/19/2023 21:37:21:   failed to load: C:/Users/test/AppData/LocalLow/IronGate/Valheim/characters_local/Steam_xxx_one.fch (Could not find file "C:\Users\test\AppData\LocalLow\IronGate\Valheim\characters_local\Steam_xxx_one.fch")

**Comment by TwentyOneZ** [comment]
Same issue here. Would it be an issue with the inverted / when trying to load?

**Comment by TwentyOneZ** [comment]
Tested it out without other mods, and it worked as it is supposed to. One of the 110 other mods are conflicting with that.
Once (if) I figure which one is the culprit, I'll post it here.

**Comment by helix22** [comment]
Yo, thanks for the input, I 'll also try it without any other mods and update the thread

**Comment by Lebaowski** [comment]
Did either of you find the conflicting mod?

**Comment by helix22** [comment]
Didn't try yet! I will update as soon as I do

**Comment by TwentyOneZ** [comment]
Sadly, no. Testing 110 mods is troublesome. 😅 
Nevertheless, I would start testing Valheim Legends. I noticed it saves character data in the "VL" folder within the characters saves folder, but I'm not sure at all. Anyone there using Valheim Legends too?

**Comment by blaxxun-boop** [comment]
The issue is that all your mods would have to support crossplay, which is very unlikely with that many mods. ServerCharacters itself does work with crossplay.
