### ISSUE TITLE
Bug in characters

### ISSUE THREAD

**Issue by werner-mayer** [blaxxun-boop/ServerCharacters#4]
Every day a few players that have already played in my server are receiving this error 

"Please create a new character, before connecting to this server, to avoid loss of data."

As i said, they have already created a new character when they played before. It's not happening with everyone or everytime, im looking with the players what they were doing when the bug appears.

**Comment by blaxxun-boop** [comment]
A few things that come to my mind, how this could happen:
The character file on the server is renamed or moved.
The character file on the client is renamed.
You are using the version of ServerBuddy that had this error message for non-whitelisted DLLs.
The users are using different Steam accounts for the same character.

**Comment by werner-mayer** [comment]
None of these options but an using another mod for check non-whitelisted dlls. 

Maybe when the dll checker reject the players, cause this bug i think, i will try that.

**Comment by werner-mayer** [comment]
Yep, another mod is throwing a connection error but Servercharacters overlap the message

**Comment by AzumattDev** [comment]
Which mod?

**Comment by AzumattDev** [comment]
Which mod?

**Comment by werner-mayer** [comment]
i friend of mine give a dll to block mods months ago. I'm going to change it to yours https://valheim.thunderstore.io/package/Azumatt/AzuAntiCheat/
