### ISSUE TITLE
Server vs Single player issue deleting items

### ISSUE THREAD

**Issue by pitchblac23** [blaxxun-boop/ServerCharacters#41]
ive noticed that if you log into a server and then play a single player world it'll remove items from that single world since its interacting with the server character first and updating with that. not sure if this is a fix on the plugin side or just how valheim is.. but does upset some friends i play with thanks in advance!

**Comment by blaxxun-boop** [comment]
So, the mod is doing exactly what it's supposed to do: Preventing players from bringing items from another world to your server. Thanks for confirming.

If you don't care about that, you can enable backup only mode in the cfg file.
