### ISSUE TITLE
Mod causes client lockups

### ISSUE THREAD

**Issue by Tchilly** [blaxxun-boop/ServerCharacters#42]
Hi

Installed this on a dedicated server + client, and every time it saves, it locks up the screen for a few seconds,
Anything particular to fix this?

**Comment by blaxxun-boop** [comment]
Nothing to do with ServerCharacters. Valheim just freezes, if the world is being saved. Takes a few ms early on, so you barely notice it, but the longer you play, the longer it takes to save. Sometimes up to 45 seconds for huge worlds.

Check this out: https://valheim.thunderstore.io/package/Smoothbrain/SmoothSave/

**Comment by Tchilly** [comment]
No, it's not Valheim. It's only when the character saves. Normal world saves stutters sometimes. But every time (10 min interval) the character saves; it hangs ALOT! Without the mod, game runs fine, with minor stutter on world save. But not really noticeable.

I've watched the lag spikes while having the log/console window open and its most definingly when the character saves.
