### ISSUE TITLE
Please Create New Character message

### ISSUE THREAD

**Issue by ValhallaCommunity** [blaxxun-boop/ServerCharacters#44]
Hey Blaxxun! 

Hope all is well!

I've had a few recent new Vikings join the community. They were having trouble joining and learned it was when creating a new character. There used to be a pop up message saying please create a new character message, idk if that was impacted from the last Valheim patch but just posting here just in case. 

Attaching screenshots to show the process of an existing character that has never connected to the world attempting to connect for the first time.

![image](https://user-images.githubusercontent.com/124803112/227778523-1900051f-1546-4a6f-801b-d96db01ec94c.png)
![image](https://user-images.githubusercontent.com/124803112/227778533-1af0097a-05eb-434f-b614-3bc4cf66595c.png)
![image](https://user-images.githubusercontent.com/124803112/227778540-e580f816-a08e-49ba-b294-e16f703fc4f9.png)
![image](https://user-images.githubusercontent.com/124803112/227778547-414c4e1d-ec12-4093-9d43-4a482405fb85.png)
![image](https://user-images.githubusercontent.com/124803112/227778554-cb293c21-daaa-4fd1-a846-30becd0c2191.png)

After typing in password, it says failed to connect, but historically it would have shown please create a new character. Once they created a new character, they got in no problems. 

Appreciate taking a peak into this!

Thank you!

**Comment by MDGamesmaster** [comment]
same

**Comment by blaxxun-boop** [comment]
If it doesn't pop up for you, it's another mod disconnecting you first for whatever reason.
