### ISSUE TITLE
[Error : BepInEx] Could not load [Server Characters 1.4.4]

### ISSUE THREAD

**Issue by darkt1981** [blaxxun-boop/ServerCharacters#49]
[Error : BepInEx] Could not load [Server Characters 1.4.4] because it is incompatible with: org.bepinex.plugins.valheim_plus

getting this error with valheim plus servers

**Comment by blaxxun-boop** [comment]
Yup, that is on purpose. If you see something like that, there is no point in reporting it, since it was placed there by the mod author intentionally. Valheim Plus is a terrible mod.

See https://github.com/blaxxun-boop/PassivePowers/issues/5 for more info.
