### ISSUE TITLE
[Bug] Disconnects

### ISSUE THREAD

**Issue by Voidheart90** [blaxxun-boop/ServerCharacters#5]
I've had to increase the frequency of saves just to make sure people were getting rolled back so much. I set it from 20 (default) to 10 minute intervals to try and counter it. Bad thing about the the disconnects that they do not leave a log mark on console.log or logoutput.log. 

This is happening on both servers, one North American and the other Europe (Identical in setup)
I know the data is compressed over chucks in data transfer, do you think some how this could be messing with the main pipeline with combined mods sending ZPackages? 

> Noticeable mods that the server uses that use traffic are EpicLoot, BetterTrader,ValheimLegends,BetterWards,Creature Level Loot Control, DropThat,SpawnThat,RRRCore

I had to service several tickets to restore characters that were naked, spawned at their bed, I had one incident where i could not restore 1 character, all backups were naked for this one character alone

This is from my server staff.
> 1) character corruptions were far and few between and usually never effected most people. It only happened on death and was isolated. This is happening every few hours to people in very different ways, not isolated to dying or even moving. 
> 
> 2) Prior to this new seed, I can count the amount of times the server randomly DC'd us for no reason, and when it did the ramifications from it were 1% of what they are now. Nothing bad happened other than having to log back in. It is now wiping our characters progress up to a full day. 
> 
> 3) Here are the ways it is happening, which tells me it is fully a character/server saving issue, as these things have NEVER happened prior to the last few days. 
> 
> a) Random DC's for various people that happen very frequently, and their characters roll back. Upon logging back in, they are always at their beds no matter where they were when they DC'd without any items they previously had in their inventory. (in one case, the items were found on the ground outside of their house, and they had not even been in that area before the DC- this specific instance was from the EU server) This has been brought up by 4 people as of 08/19/21. 3 US and 1 EU
> 
> b) When people die, they get DC'd and come back fully clothed at their beds but have lost everything from their inventory. No duplicated bodies to get items from. This has been brought up by 5 people as of 08/19/21. 3 US and 2 EU.
> 
> c) 3) People log out in one place, and then the next time they log in they are in a completely different place from where they logged out. This has been brought up by 3 people as of 08/19/21. 3 US.
> A B and C are the 3 main things people are coming to me about.. there are more, but I can't recall what was said prior to me keeping a tally. Those are just the #'s that I remember
> (sorry I know this is a lot of info Im throwing) - If you mix these issues with the one Pyrate had where it completely removed his whole house from around him and everything in his chests, critical thinking and process of elimination can tell us that the issue is very isolated to the server saving info, whether it be character info or server saves.

**Comment by blaxxun-boop** [comment]
Hey,

first of all, sorry about the terrible experience you are having.

But I have some doubts that this is caused by ServerCharacters, especially if you say that this happens, if players die. ServerCharacters doesn't have a single patch that touches player deaths.
And as you might have seen, there is plenty of log output for all kind of things related to ServerCharacters, so it should definitely log something, if it disconnects a user. At least for the emergency backup that should be created. And these emergency backups should prevent players from losing anything, if they get suddenly disconnected from the server, so it sounds strange when you say that you had to increase the save interval, because people lost their stuff, because of disconnects.

Stupid question, but are you sure that you are running ServerCharacters and not ServerSideCharacters?

Cheers.

**Comment by Voidheart90** [comment]
Yes using exactly ServerCharacters on this GitHub /ThunderStore because it has AES encryption.

I noticed during my gameplay sometimes monitoring the local character folder in AppData/LocalRoaming I'll have signature AES key file and a serverBackup extension when I've not been disconnected

During these disconnect not everyone has a signature AES and serverBackuo file created nor are they able to restore their last progress through emergency backup, which lead me to goto the characters/backup folder and restore characters manually for them because they don't have that local emergency backup

**Comment by werner-mayer** [comment]
I've came too complain about a few related things, there are few players with random disconnects and losing items with rollbacks in my server.

If the server gets down the players get rollback too. I will try decrease the save time too.

And lots of players log out in one place and when they come back they are in bed or spawn.

I dont think the disconnects are related to the mod, just the rollbacks.

**Comment by Voidheart90** [comment]
> And lots of players log out in one place and when they come back they are in bed or spawn.
Yeah our members of our server are reporting the same problem

I enabled maintenance mode which worked ok, it posted to discord hook and waited to appropriate amount of time before disconnecting everyone. In which i waited for the console.log to output to say World was saved and characters are backed up

I shut down the server to clear memory, cpu usage etc daily maintenance things. Our members of our server reported that it didn't save their character inventory, some were rolled back, some have said they sold particular items to the trader which landed back into their bags. Keep in mind some of these players logged off around 5pm - 7pm. The server maintenance i did was around 3:00 am

I extracted their characters from the backup Zip files, loaded them into local offline game to view inventory which confirmed they didnt have those specific items

**Comment by blaxxun-boop** [comment]
That makes it kinda sound like it fails to write to the character folder.
Might be a conflict with another mod as well. I remember someone saying that Valheim Legends modifies the character save files in some way, to save its data. Is there the possibility to check, if it works without Valheim Legends?

**Comment by werner-mayer** [comment]
i'm using valheim legends, i just dont know how to test it without the mod

**Comment by Voidheart90** [comment]
Have a few testing it without Valheim Legends today.
VL patches LoadPlayerFromDisk, SavePlayerFromDisk.
Directory all data from ZPackage is stored in /characters/VL/{profile}.fch

ZPackage contains Checksum + Array data. From what it looks like none of the data is written to the original character file, its all external written to /characters/VL/

**Comment by Voidheart90** [comment]
[Info   : Unity Log] 08/21/2021 13:27:05:   failed to load D:\TCAFiles\Users\briana3\5611626\/characters/{STEAMID}_.fch
[Info   : Unity Log] 08/21/2021 14:17:43:   failed to load D:\TCAFiles\Users\briana3\5611626\/characters/{STEAMID}_.fch

So it failed to load the character saves when people had connected/reconnected due to disconnections. I masked the steam id's with {.*}. Also as you will noticed their profile names are not included in the filename itself its empty string/null

**Comment by blaxxun-boop** [comment]
The profile name being empty means that the login failed for some reason. E.g. because the password was wrong or some other mod disconnected the user, before the profile was loaded. Anti-Cheat mods usually do that, as they try to disconnect the user as early as possible, so they cannot cause any harm. Are you using any of these?

Do you have any other input?

And yeah, I am using Path.DirectorySeparatorChar for pretty much all paths already, just missed one, apparently. Shouldn't be an issue, though.

**Comment by Voidheart90** [comment]
>  Anti-Cheat mods usually do that, as they try to disconnect the user as early as possible, so they cannot cause any harm. Are you using any of these?

Currently no anti-cheat. Mine is still being developed, developing my own because I don't trust obfuscated code

**Comment by Voidheart90** [comment]
``[Message:Server Characters] Maintenance mode enabled. All non-admins will be disconnected in 5 minutes.
[Error  :   BepInEx] System.IO.IOException: Sharing violation on path D:\TCAFiles\Users\danielm20\6434418\BepInEx\plugins\maintenance
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in :0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in :0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.Create (System.String path, System.Int32 bufferSize) [0x00000] in :0 
  at System.IO.File.Create (System.String path) [0x00000] in :0 
  at ServerCharacters.ServerCharacters.toggleMaintenanceMode (System.Object s, System.EventArgs e) [0x0008d] in :0 
  at (wrapper delegate-invoke) .invoke_void_object_EventArgs(object,System.EventArgs)
  at BepInEx.Configuration.ConfigEntry`1[T].<.ctor>b__10_0 (System.Object sender, BepInEx.Configuration.SettingChangedEventArgs args) [0x00013] in :0 
  at BepInEx.Configuration.ConfigFile.OnSettingChanged (System.Object sender, BepInEx.Configuration.ConfigEntryBase changedEntryBase) [0x00048] in :0 
[Message:Server Characters] Maintenance aborted
[Message:Server Characters] Maintenance mode enabled. All non-admins will be disconnected in 5 minutes.``

Went to enable Maintenance, I was curious as to why it did not post to the Discord Webhook, apparently File Exception. I had to delete the file and recreate it in order to post to the discord webhook

**Comment by werner-mayer** [comment]
i'm using azuAntiCheat only, and rollbacks are still happening when people get disconnect
