### ISSUE TITLE
Valheim Plus and ServerCharacters

### ISSUE THREAD

**Issue by LemonyLamps** [blaxxun-boop/ServerCharacters#50]
Hello, I have a server on Zap hosting and I set the server up with Valheim plus. When trying to utlize the ServerCharacters.dll nothing seems to be happening.

Here is my plugin folder on the server. 
![2023-06-19 02_00_04-lemony@147 189 168 30 - FileZilla](https://github.com/blaxxun-boop/ServerCharacters/assets/35539511/53d8573d-4303-4d16-94a3-0e44a84d033b)

I added the plugin with the server offline, started it and then shut it down after connecting with a character to look if there was anything in the config folder. I couldn't see any character saves or cfg file created for ServerCharacters. 
![2023-06-19 02_02_47-lemony@147 189 168 30 - FileZilla](https://github.com/blaxxun-boop/ServerCharacters/assets/35539511/e47dc1e4-257c-45a7-9c1f-ab9e04c763b9)

I also had the plugin on the client side, but there was no config file (if its even supposed to show up on the client side).

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose. None of my mods work with Valheim Plus and there are quite a few modders doing the same and more and more are joining in. I strongly recommend to remove Valheim Plus, it's a terrible mod and the team behind it is essentially a huge bully in the modding community.

Fore more info see https://github.com/blaxxun-boop/PassivePowers/issues/5
