### ISSUE TITLE
Maintenance Mode:- Error Saving World! Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MacTwistie** [blaxxun-boop/ServerCharacters#53]
After enabling Maintenance mode, I got this error.   Other backups are working fine.

![image](https://github.com/blaxxun-boop/ServerCharacters/assets/69218448/f328684f-f21c-4bad-af6c-5a840896733f)

**Comment by blaxxun-boop** [comment]
Was an issue with SmoothSave, which has been long fixed.
