### ISSUE TITLE
No save created when first joining

### ISSUE THREAD

**Issue by mLgz0rn** [blaxxun-boop/ServerCharacters#56]
When joining the server for the first time, it does not seem to create a savefile for that player.
It only reports back that it's unable to located the save file.

**Comment by Apollopt** [comment]
I have same issue... Im using local save instead of cloud. My friends have the same and their char is saved when the get in, mine doesnt... any clue what can it be?3

**Comment by djtreibhaus** [comment]
Same

**Comment by MDGamesmaster** [comment]
yeah having the same issue

**Comment by MDGamesmaster** [comment]
ofter 20 hours of playing i have found the culprit. its creaturelevelandlootcontrol. removed this and now saving everytime

**Comment by blaxxun-boop** [comment]
If you have crossplay enabled, make sure you only have mods installed that support it. ServerCharacters does support it, but a lot of other mods don't. And then ServerCharacters will not work properly.
