### ISSUE TITLE
Login nicht möglich

### ISSUE THREAD

**Issue by djtreibhaus** [blaxxun-boop/ServerCharacters#57]
Steht immer, Verbindung nicht möglich.
Log : 
`[Info   : Unity Log] 08/26/2023 14:00:53:   failed to load: /home/steam/.config/unity3d/IronGate/Valheim/xx/characters_local/Steam_xxxxxx_adad.fch (Could not find file "/home/steam/.config/unity3d/IronGate/Valheim/xx/characters_local/Steam_xxxx_adad.fch")
`

Warum erstellt er beim ersten login nicht den Save ?

**Comment by blaxxun-boop** [comment]
The message you've posted is vanilla output. Basically just means the file doesn't exist, so it's going to create a new one. This has nothing to do with ServerCharacters.

**Comment by djtreibhaus** [comment]
No, if I delete the plugin I can login to the server and the error isn't there.

**Comment by djtreibhaus** [comment]
without Plugin

[Info   : Unity Log] 08/27/2023 10:05:03: Network version check, their:12, mine:12

[Info   : Unity Log] 08/27/2023 10:05:03: Server: New peer connected,sending global keys

[Info   :Jotunn.Managers.SynchronizationManager+<>c__DisplayClass31_0+<<ZNet_RPC_Post_PeerInfo>g__SynchronizeInitialData|0>d] Sending initial data to peer #-862819184
[Info   : Unity Log] 08/27/2023 10:05:17: Got character ZDOID from Adad : -862819184:2

[Info   : Unity Log] 08/27/2023 10:05:22: client got keys 1

[Info   : Unity Log] 08/27/2023 10:07:27:  Connections 1 ZDOS:13850  sent:0 recv:298



_____________________ with Plugin

[Info   : Unity Log] 08/27/2023 10:25:06: Network version check, their:12, mine:12

[Info   : Unity Log] 08/27/2023 10:25:06: Server: New peer connected,sending global keys

[Info   :Jotunn.Managers.SynchronizationManager+<>c__DisplayClass31_0+<<ZNet_RPC_Post_PeerInfo>g__SynchronizeInitialData|0>d] Sending initial data to peer #-1483814759
[Info   : Unity Log] 08/27/2023 10:25:06:   failed to load: /home/steam/.config/unity3d/IronGate/Valheim/neu/characters_local/Steam_xxxxxxxx_adad.fch (Could not find file "/home/steam/.config/unity3d/IronGate/Valheim/neu/characters_local/Steam_xxxxxxx_adad.fch")

[Info   : Unity Log] 08/27/2023 10:25:06: RPC_Disconnect

[Info   :AzuExtendedPlayerInventory] Peer (xxxxx) disconnected, removing from validated list
[Info   :WardIsLove] Peer (xxxxxxx) disconnected, removing from validated list
[Info   :SimpleElevators] Peer (xxxxxx) disconnected, removing from validated list.
[Info   :EpicMMOSystem] Peer (xxxxxx) disconnected, removing from validated list
[Info   :WeightBase] Peer (xxxxxx) disconnected, removing from validated list
[Info   : Unity Log] 08/27/2023 10:25:06: Disposing socket

[Info   : Unity Log] 08/27/2023 10:25:06: Closing socket 7xxxxxx

[Info   : Unity Log] 08/27/2023 10:25:06:   send queue size:0

[Info   : Unity Log] 08/27/2023 10:25:06: Disposing socket

[Info   : Unity Log] 08/27/2023 10:25:06: Got status changed msg k_ESteamNetworkingConnectionState_None
