### ISSUE TITLE
Cannot figure out how to add modifiers in server file

### ISSUE THREAD

**Issue by Scipio71** [blaxxun-boop/ServerCharacters#59]
I am trying to turn hardcore mode on and single character mode, but I do not understand where to put these modifiers and how to enter them.

**Comment by blaxxun-boop** [comment]
It's in the mods cfg file, just like for every other mod out there.

**Comment by Scipio71** [comment]
I did that, but after I turned HardecoreMode to On, my character still respawns.  Does the mod conflict with the Hildur's Request server settings? I have it set to Hardcore in there.

Thanks!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
