### ISSUE TITLE
Getting the Valheim "Some text. Some text." error

### ISSUE THREAD

**Issue by Yarzinarak** [blaxxun-boop/ServerCharacters#60]
Running Servercharacters on a private server. Tried to log in this morning and got the "Some Text" error at the login in screen. Systematically disabled all mods minus BepinX and Servercharacters, but continued to get the same error. For context, Equipmentandquickslots by Randy Knapp causes the same error, but All other mods that we have installed on the server work just fine. Can you see any issues with Servercharacters on your end?

BepInExPack_Valheim by denikson - works
ItemDrawers by makail - works
ImmersiveCompass by Fragnarok - works
ServerCharacters by Smoothbrain - Doesn't work
EquipmentAndQuickSlots by RandyKnapp - Doesn't work

**Comment by blaxxun-boop** [comment]
Don't update Valheim on patch day.
