### ISSUE TITLE
Characters not saving - have info to help

### ISSUE THREAD

**Issue by Scipio71** [blaxxun-boop/ServerCharacters#62]
When I start a new character and its saved local, it saves it on the server.  But if the character is stored on the cloud, ServerCharacters will not save it.  So any  progress will be lost.  Also, even if you start a character as a local save, Valheim will switch it to the cloud, which creates this problem again.

**Comment by Daihok41** [comment]
I am also having this issue

**Comment by blaxxun-boop** [comment]
If you have crossplay enabled, make sure you only have mods installed that support it. ServerCharacters does support it, but a lot of other mods don't. And then ServerCharacters will not work properly.
