### ISSUE TITLE
Conflict with Valheim Plus

### ISSUE THREAD

**Issue by Blackmadman** [blaxxun-boop/ServerCharacters#63]
Is there a chance that the mod will work with Valheim Plus at some point?

**Comment by blaxxun-boop** [comment]
No. None of my mods work with Valheim Plus or ever will work with Valheim Plus. It's a terrible mod that's causing nothing but issues and it shouldn't exist.

For more info, read https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by Blackmadman** [comment]
I use Valheim Plus on my server, this version: https://www.nexusmods.com/valheim/mods/2323?tab=description
I don't have a single error message, neither on the server nor locally, everything works wonderfully, there are no lags and I haven't found a single bug.
This is just for information.
