### ISSUE TITLE
no config files or character folders

### ISSUE THREAD

**Issue by Talfereg** [blaxxun-boop/ServerCharacters#65]
Mod needs an update. Doesn't create and type of config file or character save folder or they aren't where I'd think they should be. If a character is set to cloud save then nothing at all is saved server side.

Possible that it is just incompatible with Valheim Plus

**Comment by blaxxun-boop** [comment]
Of course it's incompatible with Valheim Plus.

Valheim Plus is a piece of shit mod and a lot of mods are incompatible with that pile of crap.

**Comment by Talfereg** [comment]
> Of course it's incompatible with Valheim Plus.
> 
> Valheim Plus is a piece of shit mod and a lot of mods are incompatible with that pile of crap.

Sure bud lol. Used to work perfectly fine with V Plus. Got it all figured out now tho

**Comment by Talfereg** [comment]
Doesn't really explain why it doesn't make a BepinEx config file. That's not related to V Plus at all.
