### ISSUE TITLE
Request: Valheim Legends compatibility

### ISSUE THREAD

**Issue by TwentyOneZ** [blaxxun-boop/ServerCharacters#66]
Hey, there! Any chance that anyone would implement Valheim Legends compatibility with this mod?
It does work, but the current class and Valheim Legends skills are saved in the "characters/VL" folder, and this is not even synced with the steam cloud.

It would be awesome to make these files be server-synced too!

**Comment by blaxxun-boop** [comment]
Report that to the author of Valheim Legends.
