### ISSUE TITLE
character data not saved to server

### ISSUE THREAD

**Issue by Rummyster** [blaxxun-boop/ServerCharacters#68]
Settings are set to 1 character per steam account. However no character data is being saved to the characters_local on the server. This means only new character are allow to log in. Once that new character logs out it isn't allow to connect again because it isn't saved even after 1 hour of connection.

Server is a windows machine and proper read/write access is allowed for the locallow/Irondale folder.

**Comment by blaxxun-boop** [comment]
Disable crossplay.
