### ISSUE TITLE
Unable to connect, get sent to main menu

### ISSUE THREAD

**Issue by itsdinkd** [blaxxun-boop/ServerCharacters#70]
Installed on new server, new world. attempted to connect with new character.

I get disconnected after about 1 minute.

I tried moving my character save from cloud to local, still failed.
Tried creating a second new character, failed.

Logs;

https://pastebin.com/mxm8tKbh

**Comment by blaxxun-boop** [comment]
Yup, looks like you have a mod that prevents you from connecting to your server. I'd recommend checking the server log.

**Comment by itsdinkd** [comment]
actually that wasnt the issue, the issue was that the server was still loading, and not even on yet lol... i figured it was running after 25m but I was wrong. sorry for wasting your time.

**Comment by itsdinkd** [comment]
Where did you see a mod confliction though? i checked the logs.
