### ISSUE TITLE
Characters are not being saved in the server

### ISSUE THREAD

**Issue by Arthistic04** [blaxxun-boop/ServerCharacters#75]
Hi, can you please help us about this problem, characters created and connected to the server were not being saved. Every time we log out and logging back into the game, it prompts us to create a new character.

We checked the characters_local, nothing is in there.

We tried running the server in a different PC, it does work fine ...

**Comment by Arthistic04** [comment]
But we have crossplay enabled and it works in a different PC. We tried running the server in a different PC, it does work fine ... also the characters_local has been filled with other players character

**Comment by blaxxun-boop** [comment]
ServerCharacters works with crossplay. But as soon as you add a single mod to the mix that does not support crossplay, you will run into this issue. Just disable it.
