### ISSUE TITLE
Duplicate inventory (duplicate items)

### ISSUE THREAD

**Issue by Lime18** [blaxxun-boop/ServerCharacters#8]
How to do it:
1. Waiting "World saved"
![2](https://user-images.githubusercontent.com/29817277/136260628-521cc790-3dba-4afe-8d04-d7746ed30f7d.jpg)
2. Puts things in a chest
![1](https://user-images.githubusercontent.com/29817277/136260817-40b781f2-4eee-45e1-944c-e931557f8ac0.jpg)
![3](https://user-images.githubusercontent.com/29817277/136260772-fa71f4e0-68a5-460d-8e11-3ca2db916ddf.jpg)
3. Disconnect internet connection 
![6](https://user-images.githubusercontent.com/29817277/136261080-3e6a253a-baf9-441e-a8cf-b597601c9067.jpg)
![4](https://user-images.githubusercontent.com/29817277/136261089-fa296659-4abd-42a3-9577-4534a1a1eaf8.jpg)
4. Go to the server
![5](https://user-images.githubusercontent.com/29817277/136261191-6dbfca81-9f56-4a36-ab62-3d290cd5eb7a.jpg)
5. Profit!

**Comment by blaxxun-boop** [comment]
Server side inventory implemented in v1.1.
