### ISSUE TITLE
Character file not being created for some players

### ISSUE THREAD

**Issue by forbbidenn** [blaxxun-boop/ServerCharacters#81]
Can anyone explain to me why some players who connect to my server, their character file is not being created? I have 2 friends who try to connect to the server with a new character, and when they connect, their character's .fch file is not being created, while the others are created and updated normally... I also tried to manually put his character's fch file in the folder, he was able to enter without any problems, however, his file is not being updated and consequently every time he enters the server, he starts from 0. As if something was preventing him from sending his character's data to the server... what could it be?

**Comment by blaxxun-boop** [comment]
That happens, if you use mods that do not support playfab. Disable crossplay.
