### ISSUE TITLE
Randomly stopped saving player

### ISSUE THREAD

**Issue by MokahTGS** [blaxxun-boop/ServerCharacters#9]
We are playing on a server on a local network and for some reason this has stopped saving a character for one player reliably.  My character is saving when the world saves but this other player will only save when we sleep.  It did not save her character last night when she logged off.

Is there a way to force the mod to save via commands?  I know there is maintenance mode but anything other than that?

**Comment by Lime18** [comment]
I'll leave it here if it's ever fixed
https://www.youtube.com/watch?v=S7PyfRsx5nc
A similar problem with the fact that "some" players are not saved by the server (the profile of such a player is in the attachment
[76561197984170132_Раккета.zip](https://github.com/blaxxun-boop/ServerCharacters/files/8181092/76561197984170132_.zip)
)
